// Types of the server API, generated from its Rust structs by ts-rs: `cargo test`
// rewrites ./generated, and CI fails when the committed files are stale. Never
// edit ./generated by hand; change the Rust type instead.

export type { AcceptanceCriterion } from "./generated/AcceptanceCriterion.ts";
export type { Artifact } from "./generated/Artifact.ts";
export type { ArtifactKind } from "./generated/ArtifactKind.ts";
export type { Blocked } from "./generated/Blocked.ts";
export type { Capability } from "./generated/Capability.ts";
export type { Comment } from "./generated/Comment.ts";
export type { CommentBody } from "./generated/CommentBody.ts";
export type { CommentKind } from "./generated/CommentKind.ts";
export type { CreateBody } from "./generated/CreateBody.ts";
export type { DocLink } from "./generated/DocLink.ts";
export type { DocPage } from "./generated/DocPage.ts";
export type { DocRead } from "./generated/DocRead.ts";
export type { DocSearchResult } from "./generated/DocSearchResult.ts";
export type { DocsImpact } from "./generated/DocsImpact.ts";
export type { DocsImpactCandidate } from "./generated/DocsImpactCandidate.ts";
export type { DocsImpactReason } from "./generated/DocsImpactReason.ts";
export type { HistoryEntry } from "./generated/HistoryEntry.ts";
export type { Mail } from "./generated/Mail.ts";
export type { Member } from "./generated/Member.ts";
export type { NeedsOwner } from "./generated/NeedsOwner.ts";
export type { OwnerAction } from "./generated/OwnerAction.ts";
export type { Policy } from "./generated/Policy.ts";
export type { Publish } from "./generated/Publish.ts";
export type { Role } from "./generated/Role.ts";
export type { Status } from "./generated/Status.ts";
export type { StatusBody } from "./generated/StatusBody.ts";
export type { Task } from "./generated/Task.ts";
export type { TaskSummary } from "./generated/TaskSummary.ts";
export type { TaskType } from "./generated/TaskType.ts";
export type { Team } from "./generated/Team.ts";
export type { TeamWorktree } from "./generated/TeamWorktree.ts";
export type { UpdateBody } from "./generated/UpdateBody.ts";
export type { Worktree } from "./generated/Worktree.ts";
